### ISSUE TITLE
email notifications for completed medium and sitter registration forms

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#102]
I know we discussed this but was it ever implemented? I have not received any - thanks

**Comment by dinshaw** [comment]
Working on this.

**Comment by dinshaw** [comment]
What email would you like this to goto?

**Comment by PhranG** [comment]
robert@foreverfamilyfoundation.org  please

**Comment by dinshaw** [comment]
I fist pass it this is live. I did not have a chance to test a live one, so please do and let me know if you'd like any changes.
