### ISSUE TITLE
Comments in Event Description

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#103]
The html  "comments" markup in the Description for Events doesn't work

**Comment by dinshaw** [comment]
Where? Link please.

**Comment by PhranG** [comment]
No link but here's more detail on the issue from Kori:
When I go to the admin page, click Events, click the New Event button, then I'm able to use the Description field with the usual HTML code.  Except, if I try to comment something out (for example, sometimes I leave a placeholder for the constant contact registration page if it's not live yet) then I put  at the end of the line.  It changes color so I know it's recognizing it as a comment, but when I click "Create Event" and then go view it on the regular website, I actually see the whole line with the  around it.
