### ISSUE TITLE
Event postings

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#105]
When we create a new page we have the option to put a link into the URL field at the top.  
If we leave it blank, and the create the Event, the Title is a link to the Event Landing page on our own website.  At the very bottom of the page, **the title appears again with a link to itself**. (see Medium Explosion Webinar March 17 as an example).
If we put the Constant Contact URL in there, and then create the Event, the Title is a link to the Constant Contact page, and there is no way to see the event landing page on our website. (see Summer Grief Retreat July 16 as an example).

Are we misunderstanding how to use the Events section? What is the intended way to use the URL field?

**Comment by dinshaw** [comment]
I think the idea was that if the event had a constant contact page, the title would link to that, but if not, it would go to a fff.com page. This is as it works now. The little title at the bottom basically a bug - shouldn't be there.

If you'd like all event titles to link to the fff.com event details page, then we would have to add a link to the constant contact page from the fff.com event details page.  Does this sound like how you'd like it to work? If so, we can discuss how to display the constant contact link.

**Comment by PhranG** [comment]
Re: Closed Event postings - let's leave as is, but remove that title link at the bottom that you said was basically a bug.
