### ISSUE TITLE
finding one's profile

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#180]
Hi Dinshaw,

I know a number of issues still remain, but one is that nobody can figure out how to log into their profile. If they email us we can advise to look for a small arrow on the home page to the right of the top memu, but most don't email us. Is there a way to make it clear what the arrow is, perhaps words by arrow, enter your profile?

**Comment by dinshaw** [comment]
Hi Bob,
I was actually just working on FFF to get the deployment pipeline healthy again.
I'll change the arrow to say "Signin". It may mess up the navigation but we'll see...

**Comment by PhranG** [comment]
Thanks
