### ISSUE TITLE
profile log in

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#77]
Members cannot log into their profiles. They sign in by entering their email and password, and then get an error message
 of invalid email or password. They can click on forgot password and follow request to enter email to retrieve password, and they do get an email to change/reset password, but when they try with new password it says  “You have to confirm your email address before continuing." and they can't log in

**Comment by dinshaw-he** [comment]
I think I know what's going on here. People will need to reset their password on the new site - sorry for not realizing this. I can add a banner to the login screen to this effect.
I should be able to remove the need to confirm. I will get this today.
