### ISSUE TITLE
terms of use privacy statement does not link

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#83]
Received this from a member - 
When I looked at becoming a member, the Terms of Use & Privacy Policy and FFF Community links say they no longer exist.

**Comment by PhranG** [comment]
This is the page where there is an issue: https://www.foreverfamilyfoundation.org/users/sign_up. Also the subscription info for SOL Magazine still appears

**Comment by dinshaw** [comment]
Please open a separate issue for the Magazine thing. one problem per issue
