### ISSUE TITLE
Adding name and address info to profile

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#92]
I logged in as myself, clicked the pencil next to Personal Information, added First Name and Last Name. Clicked update.  And got an error message in pink at the top that says "Please Review Problems Below".  But it does not identify any problems.
Also, there is no way to click into Address to add one.

**Comment by dinshaw** [comment]
Appologies for this. Making the address required broke this form. Fix is deploying now.
