### ISSUE TITLE
adding image to About page

### ISSUE THREAD

**Issue by PhranG** [ForeverFamilyFoundaton/website-v2#98]
I asked Kori to add some copy to the About page, and also an image. She was unable to add the image (a photo of Phran) She tried to add a New CMS Image, it says: Error, something went wrong.

**Comment by dinshaw** [comment]
Cms Images are now working. You'll need to size them before you upload. We can add a automatic resize but first we need to figure out what size. We also can probably delete most of the existing CmsImages as I don't think many of them are used anymore. I'll need a separate Issue for that, please.
